config/routes.rb
Rails.application.routes.draw do
  


      mount Ckeditor::Engine => '/ckeditor'
      resources :gallery_types do
              resources :gallery_images do
                  collection { post :sort }
              end
       end
      resources :settings
      resources :cms_pages
      resources :users
      resources :sessions
      post   'login'   => 'sessions#create'
      get 'login', to: 'sessions#new', as: 'log_in'
      get 'logout', to: 'sessions#destroy', as: 'logout'
      resources :account_activations, only: [:edit]
      resources :password_resets,     only: [:new, :create, :edit, :show]
      post   'password_resets/:id'   => 'password_resets#update'
      get '/', to: 'users#dashboard', :as => "dashboard"
      get 'policy' => 'static_pages#policy', :as => :policy
      get 'terms' => 'static_pages#terms', :as => :terms
      get 'documentation' => 'static_pages#documentation', :as => :documentation
      get 'home' => 'static_pages#index', :as => :home
      root 'users#dashboard'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/shared/_flash.html.erb
<div class="container_flash">
  <% flash.each do |name, msg| %>
    <% if name.to_s == "error" %>
      <div class="alert alert-danger msg_content bottom-margin">
        <i class="fa fa-warning"></i> <%= msg %>
        <a class="close close_this_alert" data-dismiss="alert">×</a> 
      </div>
    <% elsif name.to_s == "notice" %>
      <div class="alert alert-success msg_content bottom-margin">
        <i class="fa fa-check"></i> <%= msg %>
        <a class="close close_this_alert" data-dismiss="alert">×</a>
      </div>
    <% elsif name.to_s == "warning" %>
      <div class="alert alert-warning msg_content bottom-margin">
        <i class="fa fa-exclamation-circle"></i> <%= msg %>
        <a class="close close_this_alert" data-dismiss="alert">×</a>
      </div>
    <% else %>
      <div class="alert alert-info msg_content bottom-margin">
        <i class="fa fa-exclamation-check"></i> <%= msg %>
        <a class="close close_this_alert" data-dismiss="alert">×</a>
      </div>
    <% end %>
  <% end %>
</div>
  

app/views/layouts/shared/_flash_msg.html.erb
<% if flash.present? %>
  <% if flash.first.present? %>      
      <%= render partial: "layouts/shared/flash", locals: {flash: flash} %>     
  <% end %>
<% end %>

app/views/layouts/shared/_header.html.erb
<div class="page-header" id="thing2">
  <div class="header-links hidden-xs">

    <div class="dropdown">
      <a href="<%= user_path(current_user["id"]) %>" class="header-link clearfix">
        <div class="avatar">
          <i class="fa fa-user"></i>
        </div>
        <div class="user-name-w">
         <%= current_user["domain_name"] %>
        </div>
      </a>
    </div>

    <div class="dropdown hidden-sm hidden-xs">
      <a href="<%= logout_path %>" class="header-link"><i class="fa fa-power-off"></i> </a>
    </div>
  </div>
  <a class="logo hidden-xs" href="<%= dashboard_path %>"><%= image_tag "innbox_icon_white.png" %></a>
  <a class="menu-toggler hidden-md hidden-lg" href="#"><i class="fa fa-bars"></i></a>
  <h1><%= image_tag "innbox_logo_white.png" %></h1>
</div>

app/views/layouts/shared/_links.html.erb
<% if controller_name != 'sessions' %>
  <%= link_to "Login", log_in_path %>&nbsp;&nbsp;&nbsp;
<% end %> 

<% unless action_name == 'new' && controller_name == 'users' %>
  <%= link_to "Sign up", new_user_path %>&nbsp;&nbsp;&nbsp;
<% end %>

<% if controller_name != 'password_resets'  %>
  <%= link_to "Forgot your password?", new_password_reset_path %><br />
<% end %>

app/views/layouts/shared/_sidebar.html.erb
<div class="side" >
      <div class="sidebar-wrapper">
            <ul>
                   <li>
                        <a href="<%= dashboard_path %>" data-toggle="tooltip" data-placement="right" title="Dashboard" data-original-title="Dashboard">
                          <i class="fa fa-home"></i>
                        </a>
                    </li>
                    <li>
                          <a href="<%= cms_pages_path%>" data-toggle="tooltip" data-placement="right" title="Contents" data-original-title="Contents">
                            <i class="fa fa-file-text-o"></i>
                          </a>
                    </li>
                    <li>
                          <a href="<%= gallery_types_path %>" data-toggle="tooltip" data-placement="right" title="Image Attributes Control" data-original-title="Image Attributes Control">
                            <i class="fa fa-file-image-o"></i>
                          </a>
                    </li>
                   <% if current_user["admin"] %>
                          <li>
                            <a href="<%= settings_path%>" data-toggle="tooltip" data-placement="right" title="" data-original-title="Settings">
                              <span class="badge"></span>
                              <i class="fa fa-code-fork"></i>
                            </a>
                          </li>
                          <li>
                            <a href="<%= users_path%>" data-toggle="tooltip" data-placement="right" title="" data-original-title="Users">
                              <i class="fa fa-users"></i>
                            </a>
                          </li>
                   <% end %>
            </ul>
      </div>
</div>

<script>
$(document).on("page:fetch", function(){
  $(".main-content").html('<i class="fa fa-spinner fa-spin" style="font-size:40px;margin-top:25%;margin-left:50%"></i>');
});

</script>