config/routes.rb
Rails.application.routes.draw do
  


      mount Ckeditor::Engine => '/ckeditor'
      resources :gallery_types do
              resources :gallery_images do
                  collection { post :sort }
              end
       end
      resources :settings
      resources :cms_pages
      resources :users
      resources :sessions
      post   'login'   => 'sessions#create'
      get 'login', to: 'sessions#new', as: 'log_in'
      get 'logout', to: 'sessions#destroy', as: 'logout'
      resources :account_activations, only: [:edit]
      resources :password_resets,     only: [:new, :create, :edit, :show]
      post   'password_resets/:id'   => 'password_resets#update'
      get '/', to: 'users#dashboard', :as => "dashboard"
      get 'policy' => 'static_pages#policy', :as => :policy
      get 'terms' => 'static_pages#terms', :as => :terms
      get 'documentation' => 'static_pages#documentation', :as => :documentation
      get 'home' => 'static_pages#index', :as => :home
      root 'users#dashboard'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/gallery_types_controller.rb
class GalleryTypesController < ApplicationController
      before_action :pass_token
      before_action :set_gallery_type, only: [:show, :edit, :update, :destroy]

      # GET /gallery_types
      # GET /gallery_types.json

      def index
        @gallery_types = GalleryType.all
      end

      # GET /gallery_types/1
      # GET /gallery_types/1.json
      def show
      end

      # GET /gallery_types/new
      def new
        @gallery_type = GalleryType.new
      end

      # GET /gallery_types/1/edit
      def edit
      end

      # POST /gallery_types
      # POST /gallery_types.json
      def create
        @gallery_type = GalleryType.create(gallery_type_params)

        respond_to do |format|
          if @gallery_type.save
            format.html { redirect_to @gallery_type, notice: 'Gallery type was successfully created.' }
            format.json { render :show, status: :created, location: @gallery_type }
          else
            format.html { render :new }
            format.json { render json: @gallery_type.errors, status: :unprocessable_entity }
          end
        end
      end

      # PATCH/PUT /gallery_types/1
      # PATCH/PUT /gallery_types/1.json
      def update
           @gallery_type.name = params[:gallery_type][:name]
           @gallery_type.height = params[:gallery_type][:height]
           @gallery_type.width = params[:gallery_type][:width]
           @gallery_type.is_video = params[:gallery_type][:is_video]
           @gallery_type.image_type = params[:gallery_type][:image_type]
          if @gallery_type.save
                 flash[:notice] =  'Gallery type was successfully updated.' 
                 redirect_to @gallery_type
          else
                 render :edit
          end
      end

      # DELETE /gallery_types/1
      # DELETE /gallery_types/1.json
      def destroy
        @gallery_type.destroy
        respond_to do |format|
          format.html { redirect_to gallery_types_url, error: 'Gallery type was successfully destroyed.' }
          format.json { head :no_content }
        end
      end

      private


          def pass_token
            @user_id = session[:user_id]
            if @user_id.class != NilClass
                GalleryType.current_user_token(session[:user_token])
            else
                redirect_to login_url
            end
          end

          # Use callbacks to share common setup or constraints between actions.
          def set_gallery_type
            @gallery_type = GalleryType.find(params[:id])
          end

          # Never trust parameters from the scary internet, only allow the white list through.
          def gallery_type_params
            params.require(:gallery_type).permit(:name, :height, :width, :is_video, :image_type)
          end
end

app/helpers/gallery_types_helper.rb
module GalleryTypesHelper
end

app/views/gallery_types/_form.html.erb
<div class="widget widget-green">
          <div class="widget-title">
            <div class="widget-controls"></div>
            <h3><i class="fa fa-ok-circle"></i> Image Attributes & Details</h3>
          </div>
          <div class="widget-content">
              <%= form_for(@gallery_type) do |f| %>
                <% if @gallery_type.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@gallery_type.errors.count, "error") %> prohibited this gallery_type from being saved:</h2>

                    <ul>
                    <% @gallery_type.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %>

                <div class="field">
                  <%= f.label :name %><br>
                  <input class="form-control" placeholder="Name" required="required" type="text" name="gallery_type[name]" id="gallery_type_name">
                </div>
                <div class="field">
                  <%= f.label :height %><br>
                  <input class="form-control" placeholder="In Pixel" required="required" type="text" name="gallery_type[height]" id="gallery_type_height">
                </div>
                <div class="field">
                  <%= f.label :width %><br>
                  <input class="form-control" placeholder="In Pixel" required="required" type="text" name="gallery_type[width]" id="gallery_type_width">
                </div>
                <div class="field">
                  <%= f.label :is_video %><br>
                  <input type="checkbox" name="gallery_type[is_video]" id="gallery_type_is_video" value="1">
                </div>
                <div class="field">
                  <%= f.label :image_type,"Media Type*(should be Unique, is used to fetch in view)"%><br>
                  <input class="form-control" placeholder="Media Type" required="required" type="text" name="gallery_type[image_type]" id="gallery_type_image_type">
                </div><br/>
                <div class="actions">
                  <%= f.submit "CREATE".html_safe, class: "btn btn-primary btn-rounded btn-iconed save_button" %>
                  <a href="<%= gallery_types_path %>" class="button btn btn-default cancel_button"> Cancel </a>
                </div>
              <% end %>
     </div>
</div>

app/views/gallery_types/edit.html.erb
<div class="main-content">
      <ol class="breadcrumb">
        <li><a href="<%= dashboard_path %>">Home</a></li>
        <li><a href="<%= gallery_types_path %>">Image Attributes Control</a></li>
        <li><a href="<%= gallery_type_path(@gallery_type) %>"><%= @gallery_type.name %></a></li>
        <li class="active">Edit</li>
      </ol>
      <% if flash.present? %>
            <%= render partial: "layouts/shared/flash", locals: {flash: flash} %>
      <% end %>
      <div class="widget widget-blue">
          <div class="widget-title">
            <div class="widget-controls">
            </div>
            <h3><i class="fa fa-ok-circle"></i> Image Attributes & Details</h3>
          </div>
          <div class="widget-content">
                <%= form_for(@gallery_type) do |f| %>
                      <% if @gallery_type.errors.any? %>
                        <div id="error_explanation">
                          <h2><%= pluralize(@gallery_type.errors.count, "error") %> prohibited this gallery_type from being saved:</h2>

                          <ul>
                          <% @gallery_type.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                          <% end %>
                          </ul>
                        </div>
                      <% end %>

                      <div class="field">
                        <%= f.label :name %><br>
                        <%= f.text_field :name ,:class => "form-control",:required => true%>
                      </div>
                      <div class="field">
                        <%= f.label :height %><br>
                        <%= f.text_field :height ,:class => "form-control",:required => true%>
                      </div>
                      <div class="field">
                        <%= f.label :width %><br>
                        <%= f.text_field :width ,:class => "form-control",:required => true%>
                      </div>
                      <div class="field">
                        <%= f.label :is_video %><br>
                         <%= f.check_box :is_video  %>
                      </div>
                      <div class="field">
                        <%= f.label :image_type,"Media Type*(should be Unique, is used to fetch in view)"%><br>
                         <%= f.text_field :image_type ,:class => "form-control",:required => true%>
                      </div><br/>
                      <div class="actions">
                        <%= f.submit "Update".html_safe, class: "btn btn-primary btn-rounded btn-iconed update_button" %>
                        <a href="<%= gallery_types_path(@gallery_type) %>" class="button btn btn-default cancel_button"> Cancel </a>
                      </div>
                    <% end %>
                </div>
           </div>

</div>

app/views/gallery_types/index.html.erb
<div class="main-content">
      <ol class="breadcrumb">
        <li><a href="<%= dashboard_path %>">Home</a></li>
        <li class="active">Image Attributes Control</li>
      </ol>
      <% if flash.present? %>
            <%= render partial: "layouts/shared/flash", locals: {flash: flash} %>
      <% end %>
    <div class="widget widget-orange">
      <div class="widget-title">
            <div class="widget-controls" >
                <%= link_to 'CREATE NEW IMAGE ATTRIBUTE', new_gallery_type_path,:class => "label label-success btn btn-success btn-rounded btn-iconed table_actions",:style => "color:white" %>
              </div>
            <h3><i class="fa fa-table"></i> Image Attributes Controls</h3>
          </div>
          <div class="widget-content">
            <div class="table-responsive">
            <table class="table table-bordered table-hover" id="gallery_type_table">
                  <thead>
                         <tr>
                                <th>Name</th>
                                <th>Height</th>
                                <th>Width</th>
                                <th>Is video</th>
                                <th>Image type</th>
                                <th></th>
                         </tr>
                  </thead>
                  <tbody>
                          <% @gallery_types.each do |gallery_type| %>
                               <tr>
                                      <td><%= gallery_type.name %></td>
                                      <td><%= gallery_type.height %></td>
                                      <td><%= gallery_type.width %></td>
                                      <td><%= gallery_type.is_video %></td>
                                      <td><%= gallery_type.image_type %></td>
                                      <td><%= link_to '<i class="fa fa-search fa-2"></i>'.html_safe, gallery_type,:class => "text-success label label-success table_actions" %>
                                            <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_gallery_type_path(gallery_type),:class => "label label-info table_actions" %>
                                            <%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, gallery_type, method: :delete, data: { confirm: 'Are you sure?' },:class => "text-danger label label-danger table_actions" %></td>
                                </tr>
                         <% end %>
                   </tbody>
            </table>
      </div>
    </div>
  </div>
</div>

<script>
jQuery(function() {
  var aoColumnDefs = [
    {
      "aTargets": [5],
      "bSortable": false
    }
  ];
  var dataTable = $('#gallery_type_table').dataTable({
    "aoColumnDefs": aoColumnDefs,
    sPaginationType: "full_numbers"
  });
});
</script>

app/views/gallery_types/new.html.erb
<div class="main-content">
      <ol class="breadcrumb">
        <li><a href="<%= dashboard_path %>">Home</a></li>
        <li><a href="<%= gallery_types_path %>">Image Attributes Control</a></li>
        <li class="active">Create New Image Attribute</li>
      </ol>
      <% if flash.present? %>
            <%= render partial: "layouts/shared/flash", locals: {flash: flash} %>
      <% end %>
    <%= render 'form' %>
</div>

app/views/gallery_types/show.html.erb
<div class="main-content">
<ol class="breadcrumb" style="border-bottom:0px solid grey !important;padding-bottom:0px !important;">
<li><a href="<%= dashboard_path %>">Home</a></li>
<li><a href="<%= gallery_types_path %>">Image Attributes Controls</a></li>
<li class="active"><%= @gallery_type.name %></li>
</ol>
<% if flash.present? %>
    <%= render partial: "layouts/shared/flash", locals: {flash: flash} %>
<% end %>
      <div class="row">
        <div class="col-md-12 col-xs-12 col-sm-12 col-lg-12">
          <table class="table invoice-table">
            <tbody>
                  <tr>
                      <th>
                    <div class="ii-name">Name</div>
                  </th>
                  <td class=""><div class="ii-name"><%= @gallery_type.name %><span class="pull-right"><%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_gallery_type_path(@gallery_type),:class => "label label-info table_actions" %></span></div></td>
              </tr>
              <tr>
                <th>
                  <div class="ii-name">Height</div>
                </th>
                <td class=""><%= @gallery_type.height %></td>
              </tr>
              <tr>
                <th>
                  <div class="ii-name">Width</div>
                </th>
                <td class=""><%= @gallery_type.width %></td>
              </tr>
              <tr>
                <th>
                  <div class="ii-name">Is video</div>
                </th>
                <td class=""><%= @gallery_type.is_video %></td>
              </tr>
               <tr>
                <th>
                  <div class="ii-name">Image type</div>
                </th>
                <td class=""><%= @gallery_type.image_type %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="widget widget-blue">
      <div class="widget-title">
         <div class="widget-controls" >
              <%= link_to 'ADD IMAGE TO GALLERY', new_gallery_type_gallery_image_path(@gallery_type),:class => "btn btn-success btn-rounded btn-iconed label label-success table_actions",:style => "color:white" %>
         </div>
         <h3><i class="fa fa-table"></i> Image Gallery</h3>
      </div>
      <div class="widget-content">
           <% if @gallery_type.gallery_images.first.present? %>
                <div class="table-responsive">
                  <table class="table table-bordered table-hover">
                        <thead>
                          <tr>
                            <th>Avatar</th>
                            <th>Title</th>
                            <th>Alt text</th>
                            <th>Link</th>
                            <th>Tags</th>
                            <th>Description</th>
                            <th></th>
                          </tr>
                        </thead>

                        <tbody id="parent-images-cats" class = "sort_images row" data-update-url="<%= sort_gallery_type_gallery_images_path(@gallery_type) %>">
                          <% @gallery_type.gallery_images.each do |gallery_image| %>
                            <%= content_tag_for(:tr, gallery_image, :class => "") do %>
                              <td>
                                      <i class="ace-icon fa fa-arrows handle" style=""></i>
                                     <%= image_tag image_url(gallery_image.avatar.gsub('original','thumb'), :host => "http://www.innboxapi.in") %></td>
                              <td><%= gallery_image.title %></td>
                              <td><%= gallery_image.alt_text %></td>
                              <td><%= gallery_image.link %></td>
                              <td><%= gallery_image.tag_list %></td>
                              <td><%= gallery_image.description %></td>
                              <td>
                                    <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_gallery_type_gallery_image_path(@gallery_type,gallery_image),:class => "label label-info table_actions" %>
                                    <%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, gallery_type_gallery_image_path(@gallery_type, gallery_image), method: :delete, data: { confirm: 'Are you sure?' },:class => "text-danger label label-danger table_actions" %></td>
                            <% end %>
                          <% end %>
                        </tbody>
                  </table>
                </div>
          <% else %>
                 <div class="text-center">NO IMAGES IN GALLERY</div>
          <% end %>
        </div>
      </div>
      <section id="layout_templates">
      <h1>Ajax call</h1>
      This section covers basic layout components: markup, classes and tags used in the theme for main skin elements. <br/><br/>
      <section id="sidebars">
      <ol>
      <li><strong>Fetch images based on gallery types </strong> <br/>
        <pre class="prettyprint">
          &lt;script&gt;
          $(document).ready(function(){
              $.ajax({
                  url: "http://www.innboxapi.in/api/v1/consumer/gallery_images",
                  data: { "gallery_type_id" : <%= @gallery_type.id %>},
                  type: "GET",
                  dataType: 'text',
                  success: function(data) { 
                    var json = $.parseJSON(data);
                    for (var i = 0; i < json.gallery_images.length; i++) { 
                    var src = "http://www.innboxapi.in/" + json.gallery_images[i].avatar.replace("original", "large"); 
                    $(".ib_<%= @gallery_type.image_type.downcase.gsub(' ', '_') %>_image_type").append("&lt;img src = "+ src +"&gt;") ;
                }
                  },
                  error: function() { alert('Failed!'); },
                  beforeSend: setHeader
              });
            });
            function setHeader(xhr) {
              xhr.setRequestHeader('Authorization', 'Token gChSWs1NvwvwSS4+hSDuwg==');
            }
          &lt;/script&gt;
        </pre>
        <p> The json it returns</p></li>
        <pre class="prettyprint">
        {"gallery_images":[{"id":7,"avatar":"/uploads/7/original_993009_10151731292814369_1211389120_n.jpg?1451893380","gallery_type_id":1,"alt_text":"baby","sort_order":1,"link":"http://coderabbits.com","description":"baby","title":"babies","tag_list":"baby"},{"id":4,"avatar":"/uploads/4/original_shipping-bg.png?1451885203","gallery_type_id":1,"alt_text":"logo","sort_order":2,"link":"http://coderabbits.com","description":"logo","title":"logo","tag_list":"logo"},{"id":5,"avatar":"/uploads/5/original_shipping-bg.png?1451468204","gallery_type_id":1,"alt_text":"logo image","sort_order":3,"link":"http://coderabbits.com","description":"logo image","title":"logo image","tag_list":"logo"},{"id":6,"avatar":"/uploads/6/original_shipping-bg.png?1451885749","gallery_type_id":1,"alt_text":"logo image","sort_order":4,"link":"http://logo image","description":"logo image","title":"logo image","tag_list":"logo, new_tag"}]}</pre>
      <li><strong>Fetch images based on tags </strong> <br/>
        <pre class="prettyprint">
          &lt;script&gt;
          $(document).ready(function(){
              $.ajax({
                  url: "http://www.innboxapi.in/api/v1/consumer/gallery_images",
                  data: { "tag_name" : "baby"},
                  type: "GET",
                  dataType: 'text',
                  success: function(data) { 
                    var json = $.parseJSON(data);
                    for (var i = 0; i < json.gallery_images.length; i++) { 
                    var src = "http://www.innboxapi.in/" + json.gallery_images[i].avatar.replace("original", "large"); 
                    $(".ib_<%= @gallery_type.image_type.downcase.gsub(' ', '_') %>_name").append("&lt;img src = "+ src +"&gt;") ;
                  }
                  },
                  error: function() { alert('Failed!'); },
                  beforeSend: setHeader
              });
            });
            function setHeader(xhr) {
              xhr.setRequestHeader('Authorization', 'Token <%= current_user['access_token'] %>');
            }
          &lt;/script&gt;
        </pre>
        <p> The json it returns</p></li>
      <li><strong>HTML elements you have to paste </strong> <br/>
      <pre class="prettyprint">
      &lt;div class="ib_<%= @gallery_type.image_type.downcase.gsub(' ', '_') %>"&gt;&lt;/div&gt;</pre></li>

       </ol></section>  
  </section>
</div>



<script>
jQuery(function() {
  return $('#parent-images-cats').sortable({
    handle: '.handle',
    update: function() {
      return $.post($(this).data('update-url'), $(this).sortable('serialize'));
    }
  });
});
</script>