config/routes.rb
Rails.application.routes.draw do
  


      mount Ckeditor::Engine => '/ckeditor'
      resources :gallery_types do
              resources :gallery_images do
                  collection { post :sort }
              end
       end
      resources :settings
      resources :cms_pages
      resources :users
      resources :sessions
      post   'login'   => 'sessions#create'
      get 'login', to: 'sessions#new', as: 'log_in'
      get 'logout', to: 'sessions#destroy', as: 'logout'
      resources :account_activations, only: [:edit]
      resources :password_resets,     only: [:new, :create, :edit, :show]
      post   'password_resets/:id'   => 'password_resets#update'
      get '/', to: 'users#dashboard', :as => "dashboard"
      get 'policy' => 'static_pages#policy', :as => :policy
      get 'terms' => 'static_pages#terms', :as => :terms
      get 'documentation' => 'static_pages#documentation', :as => :documentation
      get 'home' => 'static_pages#index', :as => :home
      root 'users#dashboard'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
require 'rubygems'
require 'active_resource'  
class Resource < ActiveResource::Base
   class << self

    def headers
      Thread.current["active.resource.currentthread.headers"] = {} if Thread.current["active.resource.currentthread.headers"].blank?
      Thread.current["active.resource.currentthread.headers"]
    end

  end
end


class User < Resource
     
     self.format = ::JsonFormatter.new(:users)
     self.site = 'http://www.innboxapi.in/api/v1'
     #self.site = 'http://localhost:3000/api/v1'

     
     attr_accessor :current_user_token, :password, :password_confirmation

     def self.current_user_token(token)
             Resource.headers['authorization'] = "Token " + "token=#{token}"
     end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
      wrap_parameters :user, include: [:domain_name, :email, :password, :password_confirmation]
      before_action :set_user, only: [:show, :edit, :update, :destroy, :dashboard]
      before_action :admin_user,     only: [:index, :destroy]

      def dashboard
      end

      # GET /users
      # GET /users.json
      def index
          @setting = Setting.first
          @users = User.all
      end
 
      # GET /users/1
      # GET /users/1.json
      def show
           if params[:switch].present?
                 tenant_name = @user.domain_name
                 @tenant_name = tenant_name.gsub! '.', '_'
                 @user = User.find(params[:id],:switch_tenant => @tenant_name)
                 flash[:notice] = 'switched successfully'
           end
      end

      # GET /users/new
      def new
          @user = User.new
      end

      # GET /users/1/edit
      def edit
      end

      # POST /users
      # POST /users.json
      def create
           if session[:user_id]
               redirect_to root_url
          else
              @user = User.create(user_params)
              respond_to do |format|
                if !@user.errors.messages.present?
                  format.html { redirect_to login_path, notice: 'Registration successfull! A message with a confirmation link has been sent to your email address. Please follow the link to activate your account.' }
                  format.json { render :show, warning: :created, location: @user }
                else
                  format.html { render :new, warning: "Registration Unsuccessfull!" }
                  format.json { render json: @user.errors.messages, warning: :unprocessable_entity }
                end
              end
          end
      end

      # PATCH/PUT /users/1
      # PATCH/PUT /users/1.json
      def update
           if params[:user][:domain_name].present?
                @user.domain_name = params[:user][:domain_name]
                if @user.save
                      flash[:notice] = " your domain_name as been successfully updated "
                else
                     flash[:warning] = " domain_name as already been taken by another user "
                end
                redirect_to user_path(@user)
           elsif params[:user][:verified].present?
                @user.verified = params[:user][:verified]
                @user.save
                flash[:notice] = " User has been verified successfully "
                redirect_to users_path
           else
                 if  both_passwords_same? && password_valid?
                      @user.password = params[:user][:password]
                      @user.save
                      flash[:notice] = " Password has been reset. "
                      redirect_to user_path(@user)
                else
                      redirect_to user_path(@user)
                end
          end
      end

      # DELETE /users/1
      # DELETE /users/1.json
      def destroy
           @user.destroy
           redirect_to users_url, notice: 'User was successfully destroyed.' 
      end

      private

          def admin_user
                redirect_to(root_url) unless current_user['admin']
          end

          def both_passwords_blank?
                params[:user][:password].blank? && 
                params[:user][:password_confirmation].blank?
           end

          def both_passwords_same?
            if  params[:user][:password] == params[:user][:password_confirmation]
                return true
             else
                flash[:warning] = " Password confirmation not same. "
                return false
             end
          end

          def password_valid?
                if params[:user][:password].length > 5
                    return true
                else
                    flash[:warning] = " Password should be minimum 6 characters "
                    return false
                end
          end

          # Use callbacks to share common setup or constraints between actions.
          def set_user
                @user_id = session[:user_id]
                if @user_id.class != NilClass
                    User.current_user_token(session[:user_token])
                    if current_user["admin"] && params[:id].present?
                       @user = User.find(params[:id])
                    else
                    @user = User.find(session[:user_id])
                    end
                else
                  redirect_to home_url
                end
          end

          # Never trust parameters from the scary internet, only allow the white list through.
          def user_params
              params.require(:user).permit(:email, :password, :password_confirmation, :domain_name, :verified)
          end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% provide(:title, 'Sign Up') %>
<% if @user.errors.any? %> 
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% @user.errors.messages.each do |message| %>
            <li><%= message[1].first['attribute'] %> <%= message[1].first['message'] %></li>
      <% end %>
      </ul>
    </div>
<% end %><br/>
<%= form_for(@user) do |f| %>
      <div class="form-group relative-w">
        <input type="text" name="user[domain_name]" id="user_domain_name" class="form-control" placeholder="Domain Name (Eg: example.com)" required>
        <i class="fa fa-user input-abs-icon"></i>
      </div>
      <div class="form-group relative-w">
        <input type="email" name="user[email]" id="user_email" class="form-control" placeholder="Enter email">
        <i class="fa fa-envelope input-abs-icon" required></i>
      </div>
      <div class="form-group relative-w">
        <input type="password" name="user[password]" id="user_password" class="form-control" placeholder="Password" required>
        <i class="fa fa-lock input-abs-icon"></i>
      </div>
      <div class="form-group relative-w">
        <input type="password" name="user[password_confirmation]" id="user_password_confirmation" class="form-control" placeholder="Confirm Password" required>
        <i class="fa fa-lock input-abs-icon"></i>
      </div>
      <div class="form-group">
        <div class="checkbox">
          <label>
            <input type="checkbox"> I agree to <a href="<%= terms_path %>">terms of use</a> and <a href="<%= policy_path %>">policy</a>.
          </label>
        </div>
      </div>
      <%= f.submit "Register Now".html_safe, class: "btn btn-gold btn-rounded btn-iconed" %>
      <div class="no-account-yet">
        Already have an account? <%= link_to "Login", log_in_path %>
      </div>
<% end %>
        

app/views/users/dashboard.html.erb
<div class="main-content">
    <ol class="breadcrumb">
      <li class="active">Dashboard</li>
    </ol>
     <% if flash.present? %>
            <%= render partial: "layouts/shared/flash", locals: {flash: flash} %>
      <% end %>
</div>

app/views/users/edit.html.erb
<div class="main-content">
      <ol class="breadcrumb">
        <li><a href="<%= dashboard_path %>">Home</a></li>
        <li><a href="<%= users_path %>">Users</a></li>
         <li><a href="<%= user_path(@user) %>"><%= @user.domain_name %></a></li>
        <li class="active">Edit</li>
      </ol>
      <% if flash.present? %>
            <%= render partial: "layouts/shared/flash", locals: {flash: flash} %>
      <% end %>
      <%= render 'form' %>
</div>

app/views/users/index.html.erb
<div class="main-content">
      <ol class="breadcrumb">
        <li><a href="<%= dashboard_path %>">Home</a></li>
        <li class="active">Users</li>
      </ol>
      <% if flash.present? %>
            <%= render partial: "layouts/shared/flash", locals: {flash: flash} %>
      <% end %>
    <div class="widget widget-orange">
      <div class="widget-title">
            <div class="widget-controls">
            </div>
            <h3><i class="fa fa-table"></i> Users Table</h3>
          </div>
          <div class="widget-content">
            <div class="table-responsive">
            <table class="table table-bordered table-hover" id="users_table">
                  <thead>
                         <tr>
                              <th>No</th>
                              <th>Domain Name</th>
                              <th>Email</th>
                              <th>Role</th>
                              <th>Created At</th>
                              <% if @setting.present? %><th>Verification</th><% end %>
                              <th>Status</th>
                              <th></th>
                         </tr>
                  </thead>
                  <tbody>
                         <% @flag = 1 %>
                         <% @users.each do |user| %> 
                               <tr>
                                      <td><%= @flag %></td>
                                      <td><%= user.domain_name %></td>
                                      <td><%= user.email %></td>
                                      <td><%= user.admin ? 'Admin' : 'User' %></td>
                                      <td><%= Date.parse(user.created_at).strftime("%d %b %Y") %></td>
                                      <% if @setting.present? %><td>  
                                      <% if user.verified == true %>Verified<% else %><%= form_for(user) do |f| %>
                                      <input type="hidden" name="user[verified]" id="verified" value="true"><input type="hidden" name="user[id]" id="verified" value="<%= user.id%>"><%= f.submit "Verify"%><% end %><% end %></td><% end %>
                                      <td>
                                      <% if user.activated? %>
                                      <span class="label label-success">Active</span>
                                      <% else %>
                                      <span class="label label-warning">Inactive</span>
                                      <% end %>
                                      </td>
                                      <td class="text-left">
                                      <%= link_to 'switch'.html_safe, user_path(user,:switch => 1),:class => "text-success label label-success table_actions" %>
                                      <%= link_to '<i class="fa fa-search fa-2"></i>'.html_safe, user_path(user),:class => "text-success label label-success table_actions" %>
                                       <%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, user, method: :delete, data: { confirm: 'Are you sure?' },:class => "text-danger label label-danger table_actions" %>
                                      </td>
                                      <% @flag = @flag +1 %>
                                </tr>
                         <% end %>
                   </tbody>
            </table>
      </div>
    </div>
  </div>
</div>


<script>
jQuery(function() {
  var aoColumnDefs = [
    {
      "aTargets": [6,7],
      "bSortable": false
    }
  ];
  var dataTable = $('#users_table').dataTable({
    "aoColumnDefs": aoColumnDefs,
    sPaginationType: "full_numbers"
  });
});
</script>

app/views/users/new.html.erb
<div class="login-logo-w">
  <a href="index.html" class="logo" style="font-size:42px;">
    Innbox
  </a>
</div>
<div class="row">
    <div class="col-md-4 col-md-offset-4">
          <div class="widget widget-gold">
            <div class="widget-title">
              <h3 class="text-center"><i class="fa fa-lock"></i>Register Now</h3>
            </div>
            <div class="widget-content">
                 <%= render 'form' %>
                 </div>
          </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="main-content">
    <ol class="breadcrumb">
      <li><a href="<%= dashboard_path %>">Home</a></li>
      <li><a href="<%= users_path%>">Users</a></li>
      <li class="active"><%= @user.domain_name %></li>
    </ol>
    <% if flash.present? %>
            <%= render partial: "layouts/shared/flash", locals: {flash: flash} %>
      <% end %>
     <div class="box">
            <ul class="nav nav-tabs">
                  <li class="active"><a href="#tab_pie_chart" data-toggle="tab"><i class="fa fa-bullseye"></i>Account Details </a></li>
                  <li><a href="#tab_table" data-toggle="tab"><i class="fa fa-table"></i> Edit Account</a></li>
                  <li><a href="#change_password" data-toggle="tab"><i class="fa fa-lock"></i> Change Password</a></li>
            </ul>
            <div class="tab-content bottom-margin">
                  <div class="tab-pane active" id="tab_pie_chart">
                        <div class="shadowed-bottom">
                                <div class="row">
                                      <div class="col-sm-3 bordered">
                                        <div class="value-block padded-left text-center">
                                          <div class="value-self"><%= @user.visits %></div>
                                          <div class="value-sub">Total Visits</div>
                                        </div>
                                      </div>
                                      <div class="col-sm-3 bordered">
                                        
                                      </div>
                                      <div class="col-sm-6">
                                        
                                      </div>
                                </div>
                        </div>
                        <div class="padded">
                                <table class="table">
                                  <thead>
                                    <tr>
                                      <th>Product</th>
                                      <th>Qty</th>
                                    </tr>
                                  </thead>
                                  <tbody>
                                    <tr>
                                      <td>Domain Name</td>
                                      <td><%= @user.domain_name %></td>
                                    </tr>
                                    <tr>
                                      <td>Email</td>
                                      <td><%= @user.email %></td>
                                    </tr>
                                    <tr>
                                      <td>Created At</td>
                                      <td><%= Date.parse(@user.created_at).strftime("%d %b %Y") %></td>
                                    </tr>
                                    <tr>
                                      <td>Activated At</td>
                                      <td><%if @user.activated_at.present? %><%= Date.parse(@user.activated_at).strftime("%d %b %Y") %><% else %>NOT YET ACTIVATED<% end %></td>
                                    </tr>
                                    <tr>
                                      <td>Access Token</td>
                                      <td><%= @user.access_token %></td>
                                    </tr>
                                  </tbody>
                                </table>
                                </div>
                          </div>
                        <div class="tab-pane" id="tab_table">
                          <div class="padded">
                              <%= form_for(@user) do |f| %>
                                    <div class="form-group relative-w">
                                      <input type="text" name="user[domain_name]" id="user_domain_name" class="form-control" placeholder="Domain Name (Eg: example.com)" required>
                                      <i class="fa fa-user input-abs-icon"></i>
                                    </div>
                                    <%= f.submit "Update".html_safe, class: "btn btn-success btn-rounded btn-iconed" %>
                                <% end %>
                          </div>
                  </div>
                  <div class="tab-pane" id="change_password">
                          <div class="padded">
                              <%= form_for(@user) do |f| %>
                                      <input type="hidden" name="user[email]" id="user_email" class="form-control" value="<%= @user.email %>">                                    
                                      <div class="form-group relative-w">
                                      <input type="password" name="user[password]" id="user_password" class="form-control" placeholder="Password" required>
                                      <i class="fa fa-lock input-abs-icon"></i>
                                    </div>
                                    <div class="form-group relative-w">
                                      <input type="password" name="user[password_confirmation]" id="user_password_confirmation" class="form-control" placeholder="Confirm Password" required>
                                      <i class="fa fa-lock input-abs-icon"></i>
                                    </div>
                                    <%= f.submit "Update".html_safe, class: "btn btn-success btn-rounded btn-iconed" %>
                                <% end %>
                          </div>
                  </div>
            </div>
        </div>
  </div>