config/routes.rb
Rails.application.routes.draw do
  


      mount Ckeditor::Engine => '/ckeditor'
      resources :gallery_types do
              resources :gallery_images do
                  collection { post :sort }
              end
       end
      resources :settings
      resources :cms_pages
      resources :users
      resources :sessions
      post   'login'   => 'sessions#create'
      get 'login', to: 'sessions#new', as: 'log_in'
      get 'logout', to: 'sessions#destroy', as: 'logout'
      resources :account_activations, only: [:edit]
      resources :password_resets,     only: [:new, :create, :edit, :show]
      post   'password_resets/:id'   => 'password_resets#update'
      get '/', to: 'users#dashboard', :as => "dashboard"
      get 'policy' => 'static_pages#policy', :as => :policy
      get 'terms' => 'static_pages#terms', :as => :terms
      get 'documentation' => 'static_pages#documentation', :as => :documentation
      get 'home' => 'static_pages#index', :as => :home
      root 'users#dashboard'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/gallery_image.rb
require 'rubygems'
require 'active_resource'  
class Resource < ActiveResource::Base
end


class GalleryImage < Resource
     
      self.format = ::JsonFormatter.new(:gallery_images)
      self.site = 'http://www.innboxapi.in/api/v1'
     #self.site = 'http://localhost:3000/api/v1'
      attr_accessor :current_user_token
      attr_writer :deferred_image
      belongs_to :gallery_type

     def self.current_user_token(token)
         Resource.headers['authorization'] = "Token " + "token=#{token}"
     end

end

app/controllers/gallery_images_controller.rb
class GalleryImagesController < ApplicationController
      before_action :set_gallery_type
      before_action :set_gallery_image, only: [:show, :edit, :update, :destroy]

      # GET /gallery_images
      # GET /gallery_images.json
      def index
           @gallery_images = @gallery_type.gallery_images
      end

      # GET /gallery_images/1
      # GET /gallery_images/1.json
      def show
      end

      # GET /gallery_images/new
      def new
            @gallery_image = GalleryImage.new
      end

      # GET /gallery_images/1/edit
      def edit
      end

      # POST /gallery_images
      # POST /gallery_images.json
      def create
            uploaded_io = params[:gallery_image][:avatar]
            File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename.gsub(" ","_")).to_s.gsub("innbox.in","innboxapi.in").gsub("innbox_client","innbox_api"), 'wb') do |file|
                  file.write(uploaded_io.read)
            end
            @gallery_image = GalleryImage.create(gallery_image_params)
            respond_to do |format|
                if @gallery_image.save
                  format.html { redirect_to gallery_type_path(@gallery_type), notice: 'Gallery image was successfully created.' }
                  format.json { render :show, status: :created, location: @gallery_image }
                else
                  format.html { render :new }
                  format.json { render json: @gallery_image.errors, status: :unprocessable_entity }
                end
             end
      end

      # PATCH/PUT /gallery_images/1
      # PATCH/PUT /gallery_images/1.json
      def update
          if params[:gallery_image][:avatar].blank?
                if params[:gallery_image][:crop_x].present?
                      @gallery_image.crop_x = params[:gallery_image][:crop_x]
                      @gallery_image.crop_y = params[:gallery_image][:crop_y]
                      @gallery_image.crop_w = params[:gallery_image][:crop_w]
                      @gallery_image.crop_h = params[:gallery_image][:crop_h]
                      @gallery_image.save
                      flash[:notice] = "Gallery image was successfully updated."
                      redirect_to gallery_type_gallery_images_url(@gallery_type)
                else
                      @gallery_image.title = params[:gallery_image][:title]
                      @gallery_image.alt_text = params[:gallery_image][:alt_text]
                      @gallery_image.link = params[:gallery_image][:link]
                      @gallery_image.description = params[:gallery_image][:description]
                      @gallery_image.tag_list = params[:gallery_image][:tag_list]
                      if @gallery_image.save
                             render :action => "crop"
                      else
                             render :edit 
                      end
                end
          else
                uploaded_io = params[:gallery_image][:avatar]
                File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename.gsub(" ","_")).to_s.gsub("innbox_client","innbox_api"), 'wb') do |file|
                      file.write(uploaded_io.read)
                end
                @gallery_image.title = params[:gallery_image][:title]
                @gallery_image.alt_text = params[:gallery_image][:alt_text]
                @gallery_image.link = params[:gallery_image][:link]
                @gallery_image.description = params[:gallery_image][:description]
                @gallery_image.avatar = params[:gallery_image][:avatar]
                if @gallery_image.save
                       @gallery_image = @gallery_type.gallery_image(@gallery_image.id)
                       render :action => "crop"
                else
                       render :edit 
                end
          end
      end

      def sort
        params[:gallery_image].each_with_index do |id, index|
          @gallery_image = @gallery_type.gallery_image(id)
          @gallery_image.sort_order =  index+1
          @gallery_image.save
        end
        render nothing: true
      end

      # DELETE /gallery_images/1
      # DELETE /gallery_images/1.json
      def destroy
            @gallery_image.destroy
            respond_to do |format|
              format.html { 
                redirect_to gallery_type_gallery_images_url(@gallery_type)
                flash[:error] = " Gallery image was successfully destroyed. " 
               }
              format.json { head :no_content }
            end
      end

      private

              # Use callbacks to share common setup or constraints between actions.
            def set_gallery_type
                  @user_id = session[:user_id]
                  if @user_id.class != NilClass
                       GalleryType.current_user_token(session[:user_token])
                       @gallery_type = GalleryType.find(params[:gallery_type_id])
                  else
                       redirect_to login_url
                  end
            end

            # Use callbacks to share common setup or constraints between actions.
            def set_gallery_image
                  @user_id = session[:user_id]
                  if @user_id.class != NilClass
                       GalleryImage.current_user_token(session[:user_token])
                      @gallery_image = @gallery_type.gallery_image(params[:id])
                  else
                       redirect_to login_url
                  end
            end

            # Never trust parameters from the scary internet, only allow the white list through.
            def gallery_image_params
                  params.require(:gallery_image).permit(:avatar, :gallery_type_id, :alt_text, :sort_order, :link, :description, :title, :crop_x, :crop_y, :crop_w, :crop_h, :tag_list)
            end
end

app/helpers/gallery_images_helper.rb
module GalleryImagesHelper
end

app/views/gallery_images/_form.html.erb
<div class="widget widget-green">
          <div class="widget-title">
            <div class="widget-controls"></div>
            <h3><i class="fa fa-ok-circle"></i> Gallery Image Form</h3>
          </div>
          <div class="widget-content">
              <%= form_for(@gallery_image, :url => gallery_type_gallery_images_path(@gallery_type), validate: true ,:html => {:multipart => true}) do |f| %>
                    <% if @gallery_image.errors.any? %>
                          <div id="error_explanation">
                            <h2><%= pluralize(@gallery_image.errors.count, "error") %> prohibited this gallery_image from being saved:</h2>

                            <ul>
                            <% @gallery_image.errors.full_messages.each do |message| %>
                              <li><%= message %></li>
                            <% end %>
                            </ul>
                           </div>
                    <% end %>

                    <div class="field">
                      <%= f.label :avatar %><br>
                       <input class="form light-form" id="gallery_image_gallery_type_id" name="gallery_image[gallery_type_id]" type="hidden" data-validate="true" value="<%= @gallery_type.id %>">
                       <input class="form light-form" id="gallery_image_avatar" name="gallery_image[avatar]" type="file" data-validate="true">
                    </div><br/>
                    <div class="field">
                      <%= f.label :title %><br>
                       <input class="form-control" id="gallery_image_title" name="gallery_image[title]" placeholder="Title" type="text" data-validate="true">
                    </div><br/>
                    <div class="field">
                      <%= f.label :alt_text %><br>
                      <input class="form-control" id="gallery_image_alt_text" name="gallery_image[alt_text]" placeholder="Alt text" type="text" data-validate="true">
                    </div><br/>
                    <div class="field">
                      <%= f.label :link %><br>
                      <input class="form-control" id="gallery_image_link" name="gallery_image[link]" placeholder="Link" type="text" data-validate="true">
                    </div><br/>
                    <div class="field">
                      <%= f.label :tag_list, "Tags (separated by commas)" %><br />
                      <input class="form-control" id="gallery_image_link" name="gallery_image[tag_list]" placeholder="Tag" type="text" data-validate="true">
                    </div><br/>
                    <div class="field">
                      <%= f.label :description %><br>
                      <textarea id="gallery_image_description" rows="5" name="gallery_image[description]" cols="40" class="form-control" ></textarea>
                    </div><br/>
                    <div class="actions">
                      <%= f.submit "CREATE".html_safe, class: "btn btn-primary btn-rounded btn-iconed save_button" %>
                      <a href="<%= gallery_type_path(@gallery_type) %>" class="button btn btn-default cancel_button"> Cancel </a>
                    </div>
              <% end %>
            </div>
     </div>

app/views/gallery_images/crop.html.erb
<div class="main-content">
      <% if flash.present? %>
            <%= render partial: "layouts/shared/flash", locals: {flash: flash} %>
      <% end %>

  <div class="clearfix ">
  <% content_for(:head) do %>
  <script type="text/javascript" charset="utf-8">
  $(function() {
    $('#cropbox').Jcrop({
      onChange: update_crop,
      onSelect: update_crop,
      setSelect: [0, 0, 100, 100],
      aspectRatio: 0
    });
  });
  function update_crop(coords) {
    var rx = 100/coords.w;
    var ry = 100/coords.h;
    $('#preview').css({
      width: Math.round(rx * <%= Paperclip::Geometry.from_file(image_url(@gallery_image.avatar.gsub('original','large'), :host => "http://www.innboxapi.in")).width %>) + 'px',
      height: Math.round(ry * <%= Paperclip::Geometry.from_file(image_url(@gallery_image.avatar.gsub('original','large'), :host => "http://www.innboxapi.in")).height %>) + 'px',
      marginLeft: '-' + Math.round(rx * coords.x) + 'px',
      marginTop: '-' + Math.round(ry * coords.y) + 'px'
    });
    var ratio = <%= Paperclip::Geometry.from_file(image_url(@gallery_image.avatar, :host => "http://www.innboxapi.in")).width %> / <%= Paperclip::Geometry.from_file(image_url(@gallery_image.avatar.gsub('original','large'), :host => "http://www.innboxapi.in")).width %>;
    $("#crop_x").val(Math.round(coords.x * ratio));
    $("#crop_y").val(Math.round(coords.y * ratio));
    $("#crop_w").val(Math.round(coords.w * ratio));
    $("#crop_h").val(Math.round(coords.h * ratio));
  }
  </script>
  <% end %>

  <%= image_tag image_url(@gallery_image.avatar.gsub('original','large'), :host => "http://www.innboxapi.in"), :id => "cropbox" %>

  <h4>Preview:</h4>
  <div style="width:100px; height:100px; overflow:hidden">
    <%= image_tag image_url(@gallery_image.avatar.gsub('original','large'), :host => "http://www.innboxapi.in"), :id => "preview",:remote => true %>
  </div>
  <%= form_for @gallery_image,:url => gallery_type_gallery_image_path(@gallery_type,@gallery_image) do |f| %>
    <% for attribute in [:crop_x, :crop_y, :crop_w, :crop_h] %>
      <%= f.hidden_field attribute, :id => attribute %>
    <% end %><br />
    <p><%= f.submit "Crop", :class => "btn btn-default btn-xs" %></p>
  <% end %>
</div>
</div>

app/views/gallery_images/edit.html.erb
<div class="main-content">
      <ol class="breadcrumb">
        <li><a href="<%= dashboard_path %>">Home</a></li>
        <li><a href="<%= gallery_types_path %>">Image Attributes Control</a></li>
        <li><a href="<%= gallery_type_path(@gallery_type) %>"><%= @gallery_type.name %></a></li>
        <li class="active"><%= @gallery_type.name %> Edit</li>
      </ol>
      <% if flash.present? %>
            <%= render partial: "layouts/shared/flash", locals: {flash: flash} %>
      <% end %>
      <div class="widget widget-blue">
          <div class="widget-title">
            <div class="widget-controls">
            </div>
            <h3><i class="fa fa-ok-circle"></i>IMAGE ATTRIBUTES & DETAILS</h3>
          </div>
          <div class="widget-content">
                <%= form_for(@gallery_image, :url => gallery_type_gallery_image_path(@gallery_type,@gallery_image), validate: true ) do |f| %>
                  <% if @gallery_image.errors.any? %>
                    <div id="error_explanation">
                      <h2><%= pluralize(@gallery_image.errors.count, "error") %> prohibited this gallery_image from being saved:</h2>

                      <ul>
                      <% @gallery_image.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                      <% end %>
                      </ul>
                    </div>
                  <% end %>

                  <div class="field">
                    <%= f.label :avatar %><br>
                    <%= f.file_field :avatar %>
                  </div><br/>
                  <div class="field">
                    <input class="form light-form" id="gallery_image_gallery_type_id" name="gallery_image[gallery_type_id]" type="hidden" data-validate="true" value="<%= @gallery_type.id %>">
                  </div><br/>
                  <div class="field">
                    <%= f.label :title %><br>
                    <%= f.text_field :title,:class => "form-control" %>
                  </div><br/>
                  <div class="field">
                    <%= f.label :alt_text %><br>
                    <%= f.text_field :alt_text,:class => "form-control"  %>
                  </div><br/>
                  <div class="field">
                    <%= f.label :link %><br>
                    <%= f.text_field :link,:class => "form-control"  %>
                  </div><br/>
                   <div class="field">
                    <%= f.label :tag_list, "Tags (separated by commas)" %><br />
                    <%= f.text_field :tag_list,:class => "form-control"  %>
                  </div><br/>
                  <div class="field">
                    <%= f.label :description %><br>
                    <%= f.text_area :description,:class => "form-control" %>
                  </div><br/>
                  <div class="actions">
                     <%= f.submit "Update".html_safe, class: "btn btn-primary btn-rounded btn-iconed update_button" %>
                      <a href="<%= gallery_types_path(@gallery_type) %>" class="button btn btn-default cancel_button"> Cancel </a>
                  </div>
                <% end %>
            </div>
      </div>
</div>

app/views/gallery_images/index.html.erb
<div class="main-content">
      <ol class="breadcrumb">
        <li><a href="<%= dashboard_path %>">Home</a></li>
        <li><a href="<%= gallery_types_path %>">Image Attributes Controls</a></li>
        <li><a href="<%= gallery_type_path(@gallery_type) %>"><%= @gallery_type.name %></a></li>
        <li class="active">Image Gallery</li>
      </ol> 
      <% if flash.present? %>
            <%= render partial: "layouts/shared/flash", locals: {flash: flash} %>
      <% end %>
    <div class="widget widget-blue">
      <div class="widget-title">
            <div class="widget-controls" style="margin-top: -10px;">
                <%= link_to 'ADD IMAGE TO GALLERY', new_gallery_type_gallery_image_path(@gallery_type),:class => "btn btn-success btn-rounded btn-iconed",:style => "color:white" %>
              </div>
            <h3><i class="fa fa-table"></i>IMAGE GALLERY</h3>
          </div>
          <div class="widget-content">
            <div class="table-responsive">
            <table class="table table-bordered table-hover">
                  <thead>
                    <tr>
                      <th>Avatar</th>
                      <th>Alt text</th>
                      <th>Link</th>
                      <th>Description</th>
                      <th>Title</th>
                      <th></th>
                    </tr>
                  </thead>

                  <tbody>
                        <% @gallery_images.each do |gallery_image| %>
                        <tr>
                            <td><%= image_tag image_url(gallery_image.avatar.gsub('original','thumb'), :host => "http://www.innboxapi.in") %></td>
                            <td><%= gallery_image.alt_text %></td>
                            <td><%= gallery_image.link %></td>
                            <td><%= gallery_image.description %></td>
                            <td><%= gallery_image.title %></td>
                            <td>
                              <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_gallery_type_gallery_image_path(@gallery_type,gallery_image),:class => "label label-info table_actions" %>
                              <%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, gallery_type_gallery_image_path(@gallery_type, gallery_image), method: :delete, data: { confirm: 'Are you sure?' },:class => "text-danger label label-danger table_actions" %>
                            </td>
                          </tr>
                        <% end %>
                  </tbody>
            </table>
          </div>
        </div>
      </div>
</div>

app/views/gallery_images/new.html.erb
<div class="main-content">
      <ol class="breadcrumb">
        <li><a href="<%= dashboard_path %>">Home</a></li>
        <li><a href="<%= gallery_types_path %>">IMAGE ATTRIBUTES & DETAILS</a></li>
        <li><a href="<%= gallery_type_path(@gallery_type) %>"><%= @gallery_type.name %></a></li>
        <li class="active">ADD IMAGE TO GALLERY</li>
      </ol>
      <% if flash.present? %>
            <%= render partial: "layouts/shared/flash", locals: {flash: flash} %>
      <% end %>
    <%= render 'form' %>
</div>

app/views/gallery_images/show.html.erb
<div class="main-content">
  <ol class="breadcrumb">
    <li><a href="<%= dashboard_path %>">Home</a></li>
    <li><a href="<%= gallery_types_path %>">Image Attributes Control</a></li>
    <li><a href="<%= gallery_type_path(@gallery_type) %>"><%= @gallery_type.name %></a></li>
    <li><a href="<%= gallery_type_gallery_images_path(@gallery_type) %>"><%= @gallery_image.title %></a></li>
    <li class="active"><%= @gallery_image.title %></li>
  </ol>
  <% if flash.present? %>
        <%= render partial: "layouts/shared/flash", locals: {flash: flash} %>
  <% end %>
  <div class="row">
      <div class="col-md-12 col-xs-12 col-sm-12 col-lg-12">
        <p>
          <strong>Avatar:</strong>
           <%= image_tag image_url(@gallery_image.avatar.gsub('original','large'), :host => "http://www.innboxapi.in") %>
        </p>

        <p>
          <strong>Gallery type:</strong>
          <%= @gallery_image.gallery_type_id %>
        </p>

        <p>
          <strong>Alt text:</strong>
          <%= @gallery_image.alt_text %>
        </p>

        <p>
          <strong>Sort order:</strong>
          <%= @gallery_image.sort_order %>
        </p>

        <p>
          <strong>Link:</strong>
          <%= @gallery_image.link %>
        </p>

        <p>
          <strong>Tags:</strong>
          <%= @gallery_image.tag_list %>
        </p>

        <p>
          <strong>Description:</strong>
          <%= @gallery_image.description %>
        </p>

        <p>
          <strong>Title:</strong>
          <%= @gallery_image.title %>
        </p>

        <%= link_to 'Edit', edit_gallery_type_gallery_image_path(@gallery_type, @gallery_image) %> |
        <%= link_to 'Back', gallery_type_gallery_images_path(@gallery_type) %>


      </div>
  </div>
  <pre class="prettyprint">
    &lt;script&gt;
      $(document).ready(function(){
        $.ajax({
            url: "http://innboxapi.in/consumer/gallery_images/<%= @gallery_type.id %>",
            data: { },
            type: "GET",
            dataType: 'text',
            success: function(data) { 
              var json = $.parseJSON(data);
              $(".gallery_images").html(json.cms_page.description) 
            },
            error: function() { alert('Failed!'); },
            beforeSend: setHeader
        });
      });
      function setHeader(xhr) {
        xhr.setRequestHeader('Authorization', 'Token <%= current_user['access_token'] %>');
      }
    &lt;/script&gt;
  </pre>
  <script>
    $(document).ready(function(){
      $.ajax({
          url: "http://innboxapi.in/consumer/gallery_images/<%= @gallery_type.id %>",
          data: { },
          type: "GET",
          dataType: 'text',
          success: function(data) { 
            var json = $.parseJSON(data);
            $(".gallery_images").html(json.cms_page.description) 
          },
          error: function() { alert('Failed!'); },
          beforeSend: setHeader
      });
    });
    function setHeader(xhr) {
      xhr.setRequestHeader('Authorization', 'Token <%= current_user['access_token'] %>');
    }
  </script>
</div>